# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - test1-web-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://publicaccesstestacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_043a5cf01b914b248d6b3482c125f1b6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b9079dfb07074ea9af1d067fda489c7b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: publicaccesstestacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_043a5cf01b914b248d6b3482c125f1b6 }}/test:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'test1-web-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cf0ab0a2aa094191b7f0363a6edf666c }}
        images: 'publicaccesstestacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_043a5cf01b914b248d6b3482c125f1b6 }}/test:${{ github.sha }}'